<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>key</string>
		<string>genkey</string>
		<string>conv</string>
		<string>rekey</string>
	</array>
	<key>name</key>
	<string>OLGA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dataTypes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.olga</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Comments - whole line or partial</string>
					<key>match</key>
					<string>((!).*$)</string>
					<key>name</key>
					<string>comment.line.number-sign.olga</string>
				</dict>
			</array>
		</dict>
		<key>connection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(CONNECTION|TERMINALS|for|return)\b</string>
					<key>name</key>
					<string>keyword.control.olga</string>
				</dict>
			</array>
		</dict>
		<key>dataTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.olga</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>String</string>
					<key>end</key>
					<string>(?&lt;!\\)"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.olga</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.olga</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Tag</string>
					<key>match</key>
					<string>[A-Za-z]+\-[0-9]+</string>
					<key>name</key>
					<string>meta.tag.object.olga</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Float</string>
					<key>match</key>
					<string>(\b\d+(\.[0-9]+)?|\.[0-9]+)([eE][+-]?[0-9]+)?</string>
					<key>name</key>
					<string>constant.numeric.float.olga</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integer</string>
					<key>match</key>
					<string>-?[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.integer.olga</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.olga</string>
	<key>uuid</key>
	<string>b21d40c0-f5fd-4687-9cdf-041150809411</string>
</dict>
</plist>
